apiVersion: v1
kind: Pod
metadata:
  name: multi-container
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: alma
    image: alma:latest
    command: ["sleep", "3600"]
    ports:
    - containerPort: 8080
