apiVersion: v1
kind: Pod
metadata:
  name: environment-vars
  labels:
    environment: production
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    env:
    - name: EKS_production_cluster 
      value: "EKS-production-cluster created by Balu Thripurari"
    - name: Telsa_production
      value: "Hi There From CEO Balu"