apiVersion: v1
kind : pod
metadata:
 name: pod-configmap
 labels:
   environment: production
   app: nginx
 annotations:
   imageregistry: "https://hub.docker.com/"
   description: "nginx pod for testing"
   team: "aws devops team"
spec:
  containers:
  - name: nginx
    image: nginx:latest
    envFrom:
        - configMapRef:
            name: configmap-pod

