apiVersion: v1
kind: Pod
metadata:
 name: pod-ref-database
 labels:
    environment: production
    app: nginx
 annotations:
    imageregistry: "https://hub.docker.com/"
    description: "nginx pod for testing"
    team: "aws devops team"

spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
      - containerPort: 80
    envFrom:
      - secretRef:
          name: db-secret